import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import { message, Modal, Collapse, Card, Col, Row } from 'antd';
import reqwest from 'reqwest';
import 'pgi/style/p-example.less';
import Cookie from 'js-cookie';
const { Panel } = Collapse;

class Example extends Component {
    constructor(props) {
        super(props);
        this.state = {
            example1: '',
            example2: '',
            example3: ''
        };
    }
    clearAllCookie() {
        var keys = document.cookie.match(/[^ =;]+(?=\=)/g);
        if (keys) {
            for (var i = keys.length; i--;)
                Cookie.remove(keys[i])
        }
    };
    componentWillMount() {
        this.clearAllCookie()
        reqwest({
            //url: 'https://premedkb.cn/api/getExample',
            url: 'https://47.101.51.25/api/getExample',
            method: 'get',
            headers: {
                "Content-Security-Policy": "upgrade-insecure-requests"
            },
            processData: false,
            success: (res) => {
                console.log(res.data)
                this.setState({
                    example1: res.data[0],
                    example2: res.data[1],
                    example3: res.data[2]
                })
            },
            error: () => {
                message.error('Error.');
            },
        });
    }
    render() {
        const example1 = "/case/report/" + this.state.example1
        const example2 = "/case/report/" + this.state.example2
        const example3 = "/case/report/" + this.state.example3
        return (
            <div className="container">
                <div style={{ fontSize: '16px', paddingRight: '20px' }}>These examples are used to get users acquainted with our system more quickly.
                Users can view the detailed formats of the files that the system requires to be uploaded in the Input part,
                    and the corresponding reports generated by the system based on the uploaded files in the Output part.</div>
                <br></br>
                <div style={{ background: '#ECECEC', padding: '30px' }}>
                    <Row gutter={24}>
                        <Col span={8}>
                            <Card title="Example 1" bordered={false}>
                                <div className="example-content">
                                    <div className="example-content-input">
                                        <b>• Input: </b>
                                        <a href="https://premedkb.cn/case/example1/premedkb-poi-example1.zip"> example1.zip </a>
                                    </div>
                                    <div className="example-content-output">
                                        <b>• Output: </b>
                                        <a href="https://premedkb.cn/poi/#/case/report/example1"> Link to the report </a>
                                        {/* <Link to={example1}>test1 </Link> */}

                                    </div>
                                    <div className="example-content-output">
                                        <b>• Description: </b>
                                        <div style={{
                                            border: '1px dashed #ddd',
                                            borderRadius: '25px',
                                            padding: '10px',
                                            fontSize: '12px',
                                            marginTop: '5px',
                                            height: '300px'
                                        }}>
                                            <span><b>Tumor Type:</b> Breast / Metastatic Triple-Negative Breast Carcinoma</span><br />
                                            <span><b>Reference Population:</b> East Asian</span><br />
                                            <span><b>Input files:</b> somatic variations, germline variations, expression profiles, TMB-H.</span><br />
                                            <span><b>Description:</b> When somatic variants are not therapeutic biomarkers, direct evidence-based drug recommendations are made based on germline variations, expression profile, and TMB status.</span><br />
                                        </div>

                                    </div>
                                </div>
                            </Card>
                        </Col>
                        <Col span={8}>
                            <Card title="Example 2" bordered={false}>
                                <div className="example-content">
                                    <div className="example-content-input">
                                        <b>• Input: </b>
                                        <a href="https://premedkb.cn/case/example2/premedkb-poi-example2.zip"> example2.zip </a>

                                    </div>
                                    <div className="example-content-output">
                                        <b>• Output: </b>
                                        <a href="https://premedkb.cn/poi/#/case/report/example2"> Link to the report </a>
                                        {/* <Link to={example2}>test2 </Link> */}
                                    </div>
                                    <div className="example-content-output">
                                        <b>• Description: </b>
                                        <div style={{
                                            border: '1px dashed #ddd',
                                            borderRadius: '25px',
                                            padding: '10px',
                                            fontSize: '12px',
                                            marginTop: '5px',
                                            height: '300px'
                                        }}>
                                            <span><b>Tumor Type:</b> Skin / Skin Cancer</span><br />
                                            <span><b>Reference Population:</b> Latino/Admixed American</span><br />
                                            <span><b>Input files:</b> somatic variations, gene fusion, TMB-H.</span><br />
                                            <span><b>Description:</b> Drug recommendations with direct evidences and inferential drugs according to indirect evidences were provided. </span><br />


                                        </div>

                                    </div>
                                </div>
                            </Card>
                        </Col>
                        <Col span={8}>
                            <Card title="Example 3" bordered={false}>
                                <div className="example-content">
                                    <div className="example-content-input">
                                        <b>• Input: </b>
                                        <a href="https://premedkb.cn/case/example3/premedkb-poi-example3.zip"> example3.zip </a>
                                    </div>
                                    <div className="example-content-output">
                                        <b>• Output: </b>
                                        <a href="https://premedkb.cn/poi/#/case/report/example3"> Link to the report </a>
                                        {/* <Link to={example3}>test3 </Link> */}
                                    </div>

                                    <div className="example-content-description">
                                        <b>• Description: </b>
                                        <div style={{
                                            border: '1px dashed #ddd',
                                            borderRadius: '25px',
                                            padding: '10px',
                                            fontSize: '12px',
                                            marginTop: '5px',
                                            height: '300px'
                                        }}>
                                            <span><b>Tumor Type:</b> Lung / Lung Adenocarcinoma</span><br />
                                            <span><b>Reference Population:</b>Other</span><br />
                                            <span><b>Input files:</b> somatic variations, CNV, TMB-H, MSI-H.</span><br />
                                            <span><b>Description:</b> Drug recommendations of direct evidences based on somatic variants and other biomarkers. </span><br />

                                        </div>
                                    </div>



                                </div>
                            </Card>
                        </Col>
                    </Row>
                </div>
                {/* <div className="example-title">
                    <b>Example 1</b>
                </div>
                <div className="example-content">
                    <div className="example-content-input">
                        <b>• Input: </b>
                        <a href="https://premedkb.cn/case/example1/premedkb-poi-report.zip"> example1.zip </a>
                    </div>
                    <div className="example-content-output">
                        <b>• Output: </b>
                        <a href="https://premedkb.cn/poi/#/case/report/example1"> Link to the report </a>

                    </div>
                </div>
                <br></br>
                <div className="example-title">
                    <b>Example 2</b>
                </div>
                <div className="example-content">
                    <div className="example-content-input">
                        <b>• Input: </b>
                        <a href="https://premedkb.cn/case/example2/premedkb-poi-report.zip"> example2.zip </a>
                    </div>
                    <div className="example-content-output">
                        <b>• Output: </b>
                        <a href="https://premedkb.cn/poi/#/case/report/example2"> Link to the report </a>
                    </div>
                </div>
                <br></br>
                <div className="example-title">
                    <b>Example 3</b>
                </div>
                <div className="example-content">
                    <div className="example-content-input">
                        <b>• Input: </b>
                        <a href="https://premedkb.cn/case/example3/premedkb-poi-report.zip"> example3.zip </a>
                    </div>
                    <div className="example-content-output">
                        <b>• Output: </b>
                        <a href="https://premedkb.cn/poi/#/case/report/example3"> Link to the report </a>
                    </div>
                </div> */}
            </div >
        )
    }
}

export default Example;